# Exercise 1 - Import Pandas library

In [ ]:
# Put your anwser here

# Exercise 2 - Read CSV file into Pandas DataFrame

In [2]:
# Put your anwser here

,RECORD_NBR,PAY_YEAR,DEPARTMENT_NO,DEPARTMENT_TITLE,JOB_CLASS_PGRADE,JOB_TITLE,EMPLOYMENT_TYPE,JOB_STATUS,MOU,MOU_TITLE,REGULAR_PAY,OVERTIME_PAY,ALL_OTHER_PAY,TOTAL_PAY,CITY_RETIREMENT_CONTRIBUTIONS,BENEFIT_PAY,GENDER,ETHNICITY
0,303030303632,2017,98,WATER AND POWER,3156-5,CUSTODIAN,FULL_TIME,ACTIVE,8,OPERATING MAINTENANCE AND SERVICE UNIT,55725.24,4785.05,2021.84,62532.13,3678.00,23508.90,FEMALE,HISPANIC
1,3030303036,2017,98,WATER AND POWER,9105-5,UTILITY ADMINISTRATOR,FULL_TIME,ACTIVE,M,MANAGEMENT EMPLOYEES UNIT,139174.88,16340.50,6170.49,161685.87,9186.00,23508.90,FEMALE,ASIAN AMERICAN
2,303030313232,2017,98,WATER AND POWER,9602-4,WATER SERVICES MANAGER,FULL_TIME,ACTIVE,M,MANAGEMENT EMPLOYEES UNIT,245879.12,0.00,12504.30,258383.42,16228.00,23508.90,MALE,BLACK
3,303030313632,2017,98,WATER AND POWER,5885-5,WTR TRTMT OPR,FULL_TIME,ACTIVE,6,STEAM PLANT AND WATER SUPPLY UNIT,101494.34,7824.99,12630.52,121949.85,6699.00,23508.90,MALE,ASIAN AMERICAN
4,303030323632,2017,98,WATER AND POWER,3841-5,ELTL MCHC,FULL_TIME,ACTIVE,8,OPERATING MAINTENANCE AND SERVICE UNIT,101345.12,22284.37,1566.75,125196.24,6689.00,23508.90,MALE,HISPANIC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685456,393936353833,2022,43,LOS ANGELES HOUSING,1223-0,ACCOUNTING CLERK,PART_TIME,ACTIVE,03,CLERICAL,12205.87,0.00,500.00,12705.87,0.00,0.00,FEMALE,ASIAN
685457,3939393534,2022,42,HARBOR,9485-0,SENIOR CIVIL ENGINEER,FULL_TIME,ACTIVE,17,SUPERVISORY PROFESSIONAL ENGINEERING AND SCIEN...,69062.40,0.00,9193.85,78256.25,20483.91,10317.36,MALE,HISPANIC
685458,3939393535,2022,4,AIRPORTS,3181-0,SECURITY OFFICER,FULL_TIME,ACTIVE,18,SAFETY / SECURITY,32927.90,4855.63,2533.37,40316.90,9766.42,4166.52,MALE,CAUCASIAN
685459,393939353733,2022,70,POLICE,2214-2,POLICE OFFICER II,FULL_TIME,ACTIVE,24,"POLICE OFFICERS, LIEUTENANT AND BELOW",39156.66,4978.06,3480.00,47614.72,17918.27,7793.89,MALE,ASIAN
685460,393939353933,2022,70,POLICE,3711-5,EQUIPMENT MECHANIC,FULL_TIME,ACTIVE,14,SERVICE AND CRAFT,40299.31,5438.40,3830.20,49567.91,11952.78,8000.64,MALE,HISPANIC

# Exercise 3 - Inspect Data Structure

In [ ]:
# Put your anwser here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 685461 entries, 0 to 685460
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   RECORD_NBR                     685461 non-null  string
 1   PAY_YEAR                       685461 non-null  int64
 2   DEPARTMENT_NO                  685461 non-null  int64
 3   DEPARTMENT_TITLE               685461 non-null  object
 4   JOB_CLASS_PGRADE               684919 non-null  object
 5   JOB_TITLE                      684919 non-null  object
 6   EMPLOYMENT_TYPE                685461 non-null  object
 7   JOB_STATUS                     685461 non-null  object
 8   MOU                            684777 non-null  string
 9   MOU_TITLE                      684712 non-null  object
 10  REGULAR_PAY                    685461 non-null  float64
 11  OVERTIME_PAY                   685027 non-null  float64
 12  ALL_OTHER_PAY                  685027 non-null  float64
 13  TOTAL_PAY                      685461 non-null  float64
 14  CITY_RETIREMENT_CONTRIBUTIONS  685461 non-null  float64
 15  BENEFIT_PAY                    685461 non-null  float64
 16  GENDER                         681600 non-null  object
 17  ETHNICITY                      681249 non-null  object
dtypes: float64(6), int64(2), object(8), string(2)
memory usage: 94.1+ MB

# Exercise 4 - Explore Data

In [ ]:
# Put your anwser here

,RECORD_NBR,PAY_YEAR,DEPARTMENT_NO,DEPARTMENT_TITLE,JOB_CLASS_PGRADE,JOB_TITLE,EMPLOYMENT_TYPE,JOB_STATUS,MOU,MOU_TITLE,REGULAR_PAY,OVERTIME_PAY,ALL_OTHER_PAY,TOTAL_PAY,CITY_RETIREMENT_CONTRIBUTIONS,BENEFIT_PAY,GENDER,ETHNICITY
0,303030303632,2017,98,WATER AND POWER,3156-5,CUSTODIAN,FULL_TIME,ACTIVE,8,OPERATING MAINTENANCE AND SERVICE UNIT,55725.24,4785.05,2021.84,62532.13,3678.0,23508.9,FEMALE,HISPANIC
1,3030303036,2017,98,WATER AND POWER,9105-5,UTILITY ADMINISTRATOR,FULL_TIME,ACTIVE,M,MANAGEMENT EMPLOYEES UNIT,139174.88,16340.50,6170.49,161685.87,9186.0,23508.9,FEMALE,ASIAN AMERICAN
2,303030313232,2017,98,WATER AND POWER,9602-4,WATER SERVICES MANAGER,FULL_TIME,ACTIVE,M,MANAGEMENT EMPLOYEES UNIT,245879.12,0.00,12504.30,258383.42,16228.0,23508.9,MALE,BLACK
3,303030313632,2017,98,WATER AND POWER,5885-5,WTR TRTMT OPR,FULL_TIME,ACTIVE,6,STEAM PLANT AND WATER SUPPLY UNIT,101494.34,7824.99,12630.52,121949.85,6699.0,23508.9,MALE,ASIAN AMERICAN
4,303030323632,2017,98,WATER AND POWER,3841-5,ELTL MCHC,FULL_TIME,ACTIVE,8,OPERATING MAINTENANCE AND SERVICE UNIT,101345.12,22284.37,1566.75,125196.24,6689.0,23508.9,MALE,HISPANIC

# Exercise 5 - Select specific columns - Pay Year, Department, Job Status, Job Title, Total Pay

In [ ]:
# Put your anwser here

,PAY_YEAR,DEPARTMENT_TITLE,JOB_STATUS,JOB_TITLE,TOTAL_PAY
0,2017,WATER AND POWER,ACTIVE,CUSTODIAN,62532.13
1,2017,WATER AND POWER,ACTIVE,UTILITY ADMINISTRATOR,161685.87
2,2017,WATER AND POWER,ACTIVE,WATER SERVICES MANAGER,258383.42
3,2017,WATER AND POWER,ACTIVE,WTR TRTMT OPR,121949.85
4,2017,WATER AND POWER,ACTIVE,ELTL MCHC,125196.24
...,...,...,...,...,...
685456,2022,LOS ANGELES HOUSING,ACTIVE,ACCOUNTING CLERK,12705.87
685457,2022,HARBOR,ACTIVE,SENIOR CIVIL ENGINEER,78256.25
685458,2022,AIRPORTS,ACTIVE,SECURITY OFFICER,40316.90
685459,2022,POLICE,ACTIVE,POLICE OFFICER II,47614.72
685460,2022,POLICE,ACTIVE,EQUIPMENT MECHANIC,49567.91

# Exercise 6 - List out all departments and get record count for each department

In [ ]:
# Put your anwser here

POLICE                                                          150016
WATER AND POWER                                                 109906
RECREATION AND PARKS                                             92359
AIRPORTS                                                         42762
FIRE                                                             42294
PUBLIC WORKS - SANITATION                                        35867
TRANSPORTATION                                                   23149
GENERAL SERVICES                                                 21103
LIBRARY                                                          18086
HARBOR                                                           13819
PUBLIC WORKS - STREET SERVICES                                   13246
CITY ATTORNEY                                                    12340
BUILDING AND SAFETY                                              12163
PUBLIC WORKS - ENGINEERING                                       10318
PERSONNEL                                                         9756
CITY CLERK                                                        8773
HOUSING AND COMMUNITY INVESTMENT DEPARTMENT                       6794
INFORMATION TECHNOLOGY AGENCY                                     6099
COUNCIL                                                           5962
CITY PLANNING                                                     4801
ZOO                                                               4465
OFFICE OF FINANCE                                                 4432
ANIMAL SERVICES                                                   4067
PUBLIC WORKS - CONTRACT ADMINISTRATION                            3922
PUBLIC WORKS - STREET LIGHTING                                    3698
MAYOR                                                             2959
CITY EMPLOYEES RETIREMENT SYSTEM                                  2844
AGING                                                             2483
CULTURAL AFFAIRS                                                  2365
CONTROLLER                                                        2346
ECONOMIC AND WORKFORCE DEVELOPMENT DEPARTMENT                     2128
PENSION                                                           2027
CITY ADMINISTRATIVE OFFICER                                       1758
LOS ANGELES HOUSING                                               1464
PUBLIC WORKS - BOARD OF PUBLIC WORKS                              1332
LOS ANGELES DEPARTMENT OF CONVENTION AND TOURISM DEVELOPMENT      1025
NEIGHBORHOOD EMPOWERMENT                                           479
EMERGENCY MANAGEMENT                                               427
EL PUEBLO DE LOS ANGELES HISTORICAL MONUMENT AUTHORITY             409
CITY ETHICS COMMISSION                                             392
DISABILITY                                                         260
CANNABIS REGULATION                                                181
COMMUNITY INVESTMENT FOR FAMILIES DEPARTMENT                       138
EMPLOYEE RELATIONS BOARD                                            89
CIVIL, HUMAN RIGHTS AND EQUITY DEPARTMENT                           38
COLISEUM/SPORTS ARENA                                               36
PUBLIC ACCOUNTABILITY                                               30
LOS ANGELES CITY TOURISM DEPARTMENT                                 19
YOUTH DEVELOPMENT DEPARTMENT                                        11
TREASURER                                                           10
COMMISSION ON CHILDREN, YOUTH AND THEIR FAMILIES                     6
ENVIRONMENTAL AFFAIRS                                                4
HUMAN RELATIONS COMMISSION                                           2
COMMISSION ON THE STATUS OF WOMEN                                    2
Name: DEPARTMENT_TITLE, dtype: int64

# Exercise 7 - Get the top 5 departments with the most record count

In [ ]:
# Put your anwser here

POLICE                  150016
WATER AND POWER         109906
RECREATION AND PARKS     92359
AIRPORTS                 42762
FIRE                     42294
Name: DEPARTMENT_TITLE, dtype: int64

# Exercise 8 - Retrieve records by row position

In [ ]:
# Put your anwser here

,index,RECORD_NBR,PAY_YEAR,DEPARTMENT_NO,DEPARTMENT_TITLE,JOB_CLASS_PGRADE,JOB_TITLE,EMPLOYMENT_TYPE,JOB_STATUS,MOU,MOU_TITLE,REGULAR_PAY,OVERTIME_PAY,ALL_OTHER_PAY,TOTAL_PAY,CITY_RETIREMENT_CONTRIBUTIONS,BENEFIT_PAY,GENDER,ETHNICITY
2,2,303030313232,2017,98,WATER AND POWER,9602-4,WATER SERVICES MANAGER,FULL_TIME,ACTIVE,M,MANAGEMENT EMPLOYEES UNIT,245879.12,0.00,12504.30,258383.42,16228.0,23508.9,MALE,BLACK
3,3,303030313632,2017,98,WATER AND POWER,5885-5,WTR TRTMT OPR,FULL_TIME,ACTIVE,6,STEAM PLANT AND WATER SUPPLY UNIT,101494.34,7824.99,12630.52,121949.85,6699.0,23508.9,MALE,ASIAN AMERICAN
4,4,303030323632,2017,98,WATER AND POWER,3841-5,ELTL MCHC,FULL_TIME,ACTIVE,8,OPERATING MAINTENANCE AND SERVICE UNIT,101345.12,22284.37,1566.75,125196.24,6689.0,23508.9,MALE,HISPANIC

# Exercise 9 - Retrieve record by index key

In [23]:
# Put your anwser here

,RECORD_NBR,PAY_YEAR,JOB_STATUS,DEPARTMENT_TITLE,JOB_TITLE,TOTAL_PAY
113172,3937353837,2013,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY III,27555.36
636310,3937353837,2021,ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,211374.24
562981,3937353837,2019,ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,190636.80
531200,3937353837,2016,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,31220.00
531199,3937353837,2016,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,133501.40
440685,3937353837,2018,ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,184781.77
685455,3937353837,2022,ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,100406.40
274247,3937353837,2017,ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,155326.40
274246,3937353837,2017,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,18732.00
411129,3937353837,2020,ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,214413.23
223480,3937353837,2015,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,30292.00
113173,3937353837,2013,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY III,103216.68
166799,3937353837,2014,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY III,90359.00
166800,3937353837,2014,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,29444.00
166798,3937353837,2014,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY III,32659.20
223479,3937353837,2015,NOT_ACTIVE,CITY ATTORNEY,DEPUTY CITY ATTORNEY IV,129939.80
168090,3939393534,2014,NOT_ACTIVE,HARBOR,CIVIL ENGINEERING ASSOCIATE III,106481.24
442273,3939393534,2018,ACTIVE,HARBOR,CIVIL ENGINEER,132138.40
275698,3939393534,2017,ACTIVE,HARBOR,CIVIL ENGINEER,129356.25
224848,3939393534,2015,NOT_ACTIVE,HARBOR,CIVIL ENGINEERING ASSOCIATE III,107573.22
532628,3939393534,2016,ACTIVE,HARBOR,CIVIL ENGINEER,97917.60
532629,3939393534,2016,NOT_ACTIVE,HARBOR,CIVIL ENGINEERING ASSOCIATE III,22656.83
114437,3939393534,2013,NOT_ACTIVE,HARBOR,CIVIL ENGINEERING ASSOCIATE III,103168.00
564414,3939393534,2019,ACTIVE,HARBOR,CIVIL ENGINEER,133560.65
654452,3939393534,2021,NOT_ACTIVE,HARBOR,CIVIL ENGINEER,109908.72
654453,3939393534,2021,ACTIVE,HARBOR,SENIOR CIVIL ENGINEER,28776.00
412851,3939393534,2020,ACTIVE,HARBOR,CIVIL ENGINEER,149584.30
685457,3939393534,2022,ACTIVE,HARBOR,SENIOR CIVIL ENGINEER,78256.25

# Exercise 10 - Retrieve all Active Job in Year 2020 with Total Pay > 300,000

In [ ]:
# Put your anwser here

,RECORD_NBR,index,PAY_YEAR,DEPARTMENT_NO,DEPARTMENT_TITLE,JOB_CLASS_PGRADE,JOB_TITLE,EMPLOYMENT_TYPE,JOB_STATUS,MOU,MOU_TITLE,REGULAR_PAY,OVERTIME_PAY,ALL_OTHER_PAY,TOTAL_PAY,CITY_RETIREMENT_CONTRIBUTIONS,BENEFIT_PAY,GENDER,ETHNICITY
327190,303137373133,327190,2020,38,FIRE,2112-3,FIREFIGHTER III,FULL_TIME,ACTIVE,23,FIREFIGHTERS AND FIRE CAPTAINS,133988.00,223739.56,6544.07,364271.63,62773.38,19611.02,MALE,CAUCASIAN
327549,3431323137,327549,2020,38,FIRE,2142-1,FIRE CAPTAIN I,FULL_TIME,ACTIVE,23,FIREFIGHTERS AND FIRE CAPTAINS,164856.00,146879.56,4627.47,316363.03,77235.04,18356.44,MALE,CAUCASIAN
327674,3537323833,327674,2020,70,POLICE,9359-0,CHIEF OF POLICE,FULL_TIME,ACTIVE,00,NON-REPRESENTED,396633.23,0.00,1200.00,397833.23,117641.42,305.30,MALE,HISPANIC
328221,3030363434,328221,2020,38,FIRE,2128-2,FIRE INSPECTOR II,FULL_TIME,ACTIVE,23,FIREFIGHTERS AND FIRE CAPTAINS,145481.60,151141.09,11829.45,308452.14,68158.13,19611.02,MALE,BLACK
328363,3030383632,328363,2020,38,FIRE,2142-1,FIRE CAPTAIN I,FULL_TIME,ACTIVE,23,FIREFIGHTERS AND FIRE CAPTAINS,160783.20,231721.49,5595.54,398100.23,75326.93,18356.20,MALE,HISPANIC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600742,393633333532,600742,2020,98,WATER AND POWER,3879-5,ELECTRIC DISTRIBUTION MECHANIC,FULL_TIME,ACTIVE,8,OPERATING MAINTENANCE AND SERVICE UNIT,140068.43,157528.80,23407.50,321004.73,9245.00,24845.07,MALE,CAUCASIAN
600812,393639353133,600812,2020,98,WATER AND POWER,3873-5,ELTC DISTRBN MCHC SUPV,FULL_TIME,ACTIVE,B,SUPERVISORY BLUE COLLAR UNIT,149779.83,179483.36,39983.65,369246.84,9885.00,24845.07,MALE,CAUCASIAN
600840,393732373532,600840,2020,98,WATER AND POWER,3873-5,ELTC DISTRBN MCHC SUPV,FULL_TIME,ACTIVE,B,SUPERVISORY BLUE COLLAR UNIT,149187.69,219828.21,54348.63,423364.53,9846.00,24442.22,MALE,BLACK
600951,393834323632,600951,2020,98,WATER AND POWER,3873-5,ELTC DISTRBN MCHC SUPV,FULL_TIME,ACTIVE,B,SUPERVISORY BLUE COLLAR UNIT,158892.81,177836.55,28805.19,365534.55,10487.00,24845.07,MALE,CAUCASIAN
601028,3939323932,601028,2020,98,WATER AND POWER,3873-5,ELTC DISTRBN MCHC SUPV,FULL_TIME,ACTIVE,B,SUPERVISORY BLUE COLLAR UNIT,153607.76,162533.06,23353.82,339494.64,10138.00,24431.66,MALE,HISPANIC

# Exercise 11 - Get active job record count of Fire and Police Department

In [ ]:
# Put your anwser here

POLICE    92067
FIRE      26776
Name: DEPARTMENT_TITLE, dtype: int64

# Exercise 12 - Get the average total pay of active job in 2021

In [ ]:
# Put your anwser here

In [28]:
payroll[(payroll["JOB_STATUS"] == "ACTIVE") & (payroll["PAY_YEAR"] == 2021)]["TOTAL_PAY"].mean()

92887.01988448336

# Exercise 13 - Which active job got the highest total pay in 2021?

In [ ]:
# Put your anwser here

,RECORD_NBR,index,PAY_YEAR,DEPARTMENT_NO,DEPARTMENT_TITLE,JOB_CLASS_PGRADE,JOB_TITLE,EMPLOYMENT_TYPE,JOB_STATUS,MOU,MOU_TITLE,REGULAR_PAY,OVERTIME_PAY,ALL_OTHER_PAY,TOTAL_PAY,CITY_RETIREMENT_CONTRIBUTIONS,BENEFIT_PAY,GENDER,ETHNICITY
324821,3437303233,324821,2021,38,FIRE,2142-1,FIRE CAPTAIN I,FULL_TIME,ACTIVE,23,FIREFIGHTERS AND FIRE CAPTAINS,160451.2,420054.86,1686.0,582192.06,75171.39,11121.6,MALE,BLACK

# Exercise 14 - List out the average of total pay between male and female for each department

In [ ]:
# Put your anwser here

DEPARTMENT_TITLE              GENDER
AGING                         FEMALE     17152.026521
                              MALE       20824.169747
AIRPORTS                      FEMALE     60382.733712
                              MALE       77559.839284
ANIMAL SERVICES               FEMALE     49005.644082
                                            ...
WATER AND POWER               MALE      113282.815733
YOUTH DEVELOPMENT DEPARTMENT  FEMALE     22295.524000
                              MALE       53524.700000
ZOO                           FEMALE     33864.337534
                              MALE       42402.344986
Name: TOTAL_PAY, Length: 112, dtype: float64

# Exercise 15 - Show average total pay of each year (column) by department (row)

In [ ]:
# Put your anwser here

PAY_YEAR,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
DEPARTMENT_TITLE,,,,,,,,,,
AGING,17464.298583,15605.107703,16954.081308,12287.633961,17900.403910,18726.084318,20275.839341,30204.216497,31861.680727,16811.599110
AIRPORTS,74057.612162,77863.238864,74675.275077,71738.412167,68040.254073,60352.738566,73266.604791,83507.194290,85152.965401,43804.041935
ANIMAL SERVICES,54110.481597,60369.391771,50662.450101,50090.316841,51498.808878,44229.211361,44271.021551,54871.030000,59027.324961,32653.751494
BUILDING AND SAFETY,79798.501172,73383.449927,74945.259470,72770.089626,77620.397324,64381.021027,81111.511195,84820.323943,96920.330494,49010.785558
CANNABIS REGULATION,NaN,NaN,NaN,NaN,52343.120000,46125.697857,45182.236316,53340.972400,65892.189000,36908.245789
CITY ADMINISTRATIVE OFFICER,71144.444364,89280.860278,74267.196517,78013.769091,73256.024339,69791.553610,72680.895392,96086.137443,89027.910877,49679.733933
CITY ATTORNEY,95153.155934,92356.079147,96319.925947,88912.946212,73711.735835,93487.098700,113268.428969,118640.326478,123418.004179,62934.460075
CITY CLERK,5114.196060,19398.609257,6115.853929,22878.315932,6953.607194,34929.188956,34775.572836,46734.607762,54643.160602,23260.623419
CITY EMPLOYEES RETIREMENT SYSTEM,56331.472587,54502.849182,52077.347025,54035.713592,47852.418191,45410.368903,52391.038799,46138.105570,59659.696523,26241.961378
CITY ETHICS COMMISSION,66821.040645,86007.610769,52992.580667,61558.319500,61657.975116,54753.506078,79542.836944,79535.790889,87818.061081,42851.114211
CITY PLANNING,69507.794277,61835.647781,67476.215160,60818.040303,60697.952371,59741.728654,66997.153067,75742.780973,81286.072949,40389.308595
"CIVIL, HUMAN RIGHTS AND EQUITY DEPARTMENT",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61192.572143,32921.150833
COLISEUM/SPORTS ARENA,37559.696944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"COMMISSION ON CHILDREN, YOUTH AND THEIR FAMILIES",NaN,NaN,NaN,NaN,NaN,58.540000,NaN,NaN,NaN,NaN
COMMISSION ON THE STATUS OF WOMEN,NaN,NaN,NaN,NaN,NaN,26.190000,NaN,NaN,NaN,NaN
COMMUNITY INVESTMENT FOR FAMILIES DEPARTMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26868.971452,37912.041316
CONTROLLER,74150.594870,77979.084583,70528.874064,62095.879919,62396.008701,50621.262130,60248.111465,69035.207794,87168.458743,44376.000773
COUNCIL,41635.597410,50429.821288,47919.546287,59679.838729,51776.640792,43353.979508,50675.948443,53961.890000,58173.103419,34502.743014
CULTURAL AFFAIRS,27675.892866,26705.492840,24058.596990,20289.252959,25474.823049,23777.718968,24411.155690,25773.324114,31679.933927,16377.441449
DISABILITY,75424.918824,82553.757222,83528.047647,69325.836190,60646.319643,53834.420286,66827.305625,87005.934242,90451.032333,45418.677931
ECONOMIC AND WORKFORCE DEVELOPMENT DEPARTMENT,52021.498106,55332.712659,68693.951183,68778.587228,61074.151914,47346.546103,68687.254973,72865.116927,77452.423642,38236.859786
EL PUEBLO DE LOS ANGELES HISTORICAL MONUMENT AUTHORITY,28624.680732,29655.778205,26440.061304,34370.834324,34751.383077,27843.325833,28996.539565,28141.107800,36359.401250,18106.981290
EMERGENCY MANAGEMENT,55306.219783,63601.011000,60158.626522,66511.427778,71356.106341,57963.962857,81726.513000,90934.070435,69730.557561,35909.112121
EMPLOYEE RELATIONS BOARD,30563.053750,29764.347778,32868.218889,30527.725556,38359.857500,29743.960000,42570.022500,43420.364444,45457.087500,22188.028750
ENVIRONMENTAL AFFAIRS,NaN,NaN,NaN,NaN,NaN,139.795000,NaN,NaN,NaN,NaN
FIRE,149478.564888,152655.087056,148558.665831,128003.535800,132967.546808,137928.313830,148070.568179,168263.969868,178170.334715,82264.005228
GENERAL SERVICES,57807.830000,62281.773894,58516.212375,57391.332011,58394.193734,44464.301399,58036.408881,67963.413672,68997.562128,36337.455716
HARBOR,73165.939950,76950.319042,71634.567954,75432.588043,71533.919557,66569.601175,73604.682352,89142.743483,100217.717369,54066.815156
HOUSING AND COMMUNITY INVESTMENT DEPARTMENT,66184.999861,72121.424823,66264.633397,57158.889403,59746.621871,58248.018983,61180.286088,70359.758977,NaN,NaN
HUMAN RELATIONS COMMISSION,NaN,NaN,NaN,NaN,NaN,81.500000,NaN,18.670000,NaN,NaN
INFORMATION TECHNOLOGY AGENCY,90005.045580,88074.938870,83195.426440,79763.165737,77859.056264,53994.253660,71700.052246,79713.136539,85204.174933,44628.534901
LIBRARY,35739.265295,41375.337636,38107.919786,36076.345293,35204.906936,32775.306985,37518.002700,41318.555665,49675.131003,22644.896945
LOS ANGELES CITY TOURISM DEPARTMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,132980.182000,68261.727778
LOS ANGELES DEPARTMENT OF CONVENTION AND TOURISM DEVELOPMENT,26056.320635,9368.744198,22349.637241,37444.769412,39968.560588,8115.090424,32478.985676,92640.370000,NaN,NaN
LOS ANGELES HOUSING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76729.802551,40688.043240
MAYOR,45165.419132,55735.210917,56488.585702,57002.561853,58806.413298,47702.794757,55384.662005,65728.110145,58279.755394,34142.775900
NEIGHBORHOOD EMPOWERMENT,42408.659286,46545.079318,37135.161667,39633.854815,46634.785349,46224.080926,38145.915147,54702.626078,64398.602432,36002.165000
OFFICE OF FINANCE,64863.957547,66639.977720,61587.560023,59769.657484,61673.853446,53768.718057,56813.626600,73031.931222,75659.531085,42464.821532
PENSION,65474.174645,64483.680778,61609.015027,60411.489343,53373.395696,54789.528178,66489.877659,65776.365066,76233.151327,32430.306335
PERSONNEL,54296.572126,54244.812679,50761.242046,47601.753049,49895.397901,39913.713601,47431.976429,55720.223043,58344.949118,31891.849789
POLICE,89623.117844,88194.746377,94796.926134,90957.943570,94676.762191,94116.434725,100819.080515,114645.818418,112642.610200,58755.484670
PUBLIC ACCOUNTABILITY,NaN,NaN,NaN,NaN,67348.224000,164783.344000,162953.314000,169412.608000,163276.470000,86611.712000
PUBLIC WORKS - BOARD OF PUBLIC WORKS,74701.243778,72277.414752,62661.143770,65190.847680,56243.323725,54109.007831,60707.727531,70979.564250,80045.832302,40710.865591
PUBLIC WORKS - CONTRACT ADMINISTRATION,86540.824377,89278.846747,85322.816377,81294.313028,68627.805588,65227.920578,76785.448039,98303.849207,95792.134191,50945.235449
PUBLIC WORKS - ENGINEERING,86712.408346,83775.765301,82464.443258,83863.939495,79770.062186,60451.169018,73792.761048,92041.570449,90108.442431,50640.894002
PUBLIC WORKS - SANITATION,66133.170455,68870.514029,64392.940538,65750.784732,63452.012905,58025.875262,66655.048904,77387.236752,83786.810450,43180.392178
PUBLIC WORKS - STREET LIGHTING,67938.119420,73448.628556,70037.860103,70468.288476,72210.679054,53744.938639,69098.842565,85993.569869,80740.184222,44132.641278
PUBLIC WORKS - STREET SERVICES,75606.745404,82252.733209,71050.233458,66650.392048,67992.280693,51891.523724,65577.285320,76757.819204,78458.674228,45092.147078
RECREATION AND PARKS,18803.015428,18183.680129,17337.383746,12935.788807,17969.518031,17180.651125,18404.788116,19710.146283,21029.652471,11025.610259
TRANSPORTATION,59164.942053,61041.581245,57236.609858,58249.172187,51887.324958,50201.641927,48802.777684,59646.049772,64479.605030,35783.244002
TREASURER,NaN,NaN,NaN,NaN,NaN,198.490000,1015.480000,146.130000,NaN,NaN
WATER AND POWER,103459.953147,103810.042141,104392.810157,103223.151194,107457.599292,117599.133038,119727.232432,113284.248904,81986.075960,NaN
YOUTH DEVELOPMENT DEPARTMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4299.450000,37040.305714
ZOO,44203.411845,43465.234918,38679.646814,32480.092964,37102.869889,32699.022810,35146.543966,40966.430766,46778.928645,25585.116793